travis:
  secure:
    BINSTAR_TOKEN: dAi7P4LBXyBBQweF3aJpCA+FokpzSOn4x3DJtDEZM14JD6rzjKXyffxZXwl8vQcYbaOZPRvZjY5Xpp9NxcdGh46VCbiSu37SI4AYd0K8OARkfzxpGQz7sSZgsq2gKZRPGjSR+En+e2r2NG5Xi6yqH+ovWLRCqOB1q0OS239wM13zchbMdWX+kn4Qwm4etlO2dDctGRXo6Q6XFgkP59fMi7sCy/1MM3WfHQB0Xjcwyl2BzgxDe8UE7OJwAy0p5hSvjMkaZBkFNj6/W9k4EvsRua3p4h942Im6pSIq+PDEa2J9hJCRl4JS616bzaMP4I7IFDRBpp54Q0ZFCVMjHHxhNHvEEV6KX9Tasg92myto5tzU9gmURV3+hzSYc5YvLL5JE7tWymCXG9SMFjKnHLlMBckyOsnHcYaJFzpuqXaLOyIt6psbAQ1oV5/1Lqu4G/PJY8JUvyQZmS4+cj8FvSNovnqd8b9hr/y//DhjfCBRH0/2MUkwLhhGHEAHAygvshCj+6tAmbLe+Af5FrdSwilLWVewfgfzof3uYGJuPLL8RKSP/rWTHCKcZBeuawuAKb8K+L9fulxp6c6dFNuRQNBAHKVo+v791hH77pjTM/UC0gUdNLJI6w804Mk+xdlDDYiRE52KVVw0LnVPFdR7srKUpDm2m+ntRclUqoXvop5wncY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
